version: "3.7"

services:

  optalgo-db:
    container_name: optalgo-db
    image: mongo:4.0
    ports:
      - 27018:27017

  optalgo-backend:
    container_name: optalgo-backend
    build: OptAlgoBackendPlay/target/docker/stage
    ports:
      - 9000:9000
    environment:
      MONGODB_HOST: optalgo-db
      MONGODB_PORT: 27017
    depends_on:
      - optalgo-db

  optalgo-frontend:
    container_name: optalgo-frontend
    build: optalgo-frontend-react
    volumes:
      - ./optalgo-frontend-react:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_HOST: localhost
      REACT_APP_API_PORT: 9000
    depends_on:
      - optalgo-backend
