version: "3.7"

services:

  bin-packing-db:
    container_name: bin-packing-db
    image: mongo:4.0
    ports:
      - 27018:27017

  bin-packing-backend:
    container_name: bin-packing-backend
    build: bin-packing-backend-play/target/docker/stage
    ports:
      - 9000:9000
    environment:
      MONGODB_URI: mongodb://bin-packing-db:27017
    depends_on:
      - bin-packing-db

  bin-packing-frontend:
    container_name: bin-packing-frontend
    build: bin-packing-frontend-react
    volumes:
      - ./bin-packing-frontend-react:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URL: http://localhost:9000
    depends_on:
      - bin-packing-backend
